services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Fixture\AppUserFixture:
        arguments:
            $exampleFactory: '@App\Factory\AppUserFactory'
            $objectManager: '@doctrine.orm.entity_manager'
