# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session: true
    serializer:
        enable_attributes: false
        enabled: true
        mapping:
            paths: [ '%kernel.project_dir%/config/serialization/' ]

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
