# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: media/cache
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/uploads/'

    driver: imagick
    default_image: /images/no_image.png
    filter_sets:
        cache: ~
        avatar:
            quality: 100
            filters:
                strip: ~
                thumbnail: { size: [ 64, 64 ], mode: outbound, allow_upscale: true, width: 64, height: 64 }
