sylius_user:
    resources:
        user:
            user:
                classes:
                    model: App\Entity\User\AppUser
        admin:
            user:
                classes:
                    model: App\Entity\User\AppUser

sylius_customer:
    resources:
        customer:
            classes:
                model: App\Entity\User\AppCustomer
        customer_group:
            classes:
                model: App\Entity\User\AppCustomerGroup
