sylius_fixtures:
    suites:
        add_user:
            listeners:
                orm_purger: false
                logger: ~
            fixtures:
                user_user:
                    name: "user_user"
                    options:
                        custom:
                            -
                                email: "learn_sylius@example.com"
                                password: "Test123!#"
                                enabled: true
                                first_name: "Coraline"
                                last_name: "Hava"
                                role: 'ROLE_ADMIN'
                            -   email: "learn_sylius_user@example.com"
                                password: "Test123!#"
                                enabled: true
                                first_name: "Herik"
                                last_name: "Tyson"
                                role: 'ROLE_USER'
