vich_uploader:
    db_driver: orm
    storage: gaufrette
    twig: true
    metadata:
        type: attribute
    mappings:
        media_files:
            uri_prefix: /media
            upload_destination: media_fs
            namer: vich_uploader.namer_uniqid
            inject_on_load: true

