resources:
    App\Entity\Cms\Config:
        shortName: 'Config'
        description: 'App config'
#        security: 'is_granted("ROLE_USER")'
        attributes:
            pagination_client_items_per_page: true
            pagination_items_per_page: 25
            pagination_enabled: true

        collectionOperations:
            get:
                method: GET
                normalization_context:
                    groups:
                        - 'config:list_read'
                openapi_context:
                    summary: "Get list of all configs"
        itemOperations:
            get:
                method: GET
                normalization_context:
                    groups:
                        - 'config:item_read'
                openapi_context:
                    summary: "Get config by id"
        identifier:
            id:
                identifier: true
