App\Entity\Cms\Config:
    attributes:
        id:
            groups:
                - 'config:list_read'
                - 'config:item_wread'
        keyword:
            groups:
                - 'config:list_read'
                - 'config:item_read'
        value:
            groups:
                - 'config:list_read'
                - 'config:item_read'
